apiVersion: v1
kind: Service
metadata:
  name: todoapi
  namespace: apps
  labels:
    app: todoapi-v1
spec:
  selector:
    app: todoapi-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi
  namespace: apps
  labels:
    app: todoapi-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapi-v1
  template:
    metadata:
      labels:
        app: todoapi-v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: todoapi
        image: 869280000980.dkr.ecr.ap-southeast-2.amazonaws.com/appd-sandbox/todoapi:latest
        ports:
        - containerPort: 80
